/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import java.util.*;
import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class AComponentDefinitions extends PComponentDefinitions
{
    private final LinkedList<PComponentDefinition> _componentDefinition_ = new LinkedList<PComponentDefinition>();

    public AComponentDefinitions()
    {
        // Constructor
    }

    public AComponentDefinitions(
        @SuppressWarnings("hiding") List<PComponentDefinition> _componentDefinition_)
    {
        // Constructor
        setComponentDefinition(_componentDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AComponentDefinitions(
            cloneList(this._componentDefinition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComponentDefinitions(this);
    }

    public LinkedList<PComponentDefinition> getComponentDefinition()
    {
        return this._componentDefinition_;
    }

    public void setComponentDefinition(List<PComponentDefinition> list)
    {
        this._componentDefinition_.clear();
        this._componentDefinition_.addAll(list);
        for(PComponentDefinition e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._componentDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._componentDefinition_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PComponentDefinition> i = this._componentDefinition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComponentDefinition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
