/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class AComponentDefinitionElementComponentDefinitionList extends PComponentDefinitionList
{
    private PComponentDefinitionElement _componentDefinitionElement_;

    public AComponentDefinitionElementComponentDefinitionList()
    {
        // Constructor
    }

    public AComponentDefinitionElementComponentDefinitionList(
        @SuppressWarnings("hiding") PComponentDefinitionElement _componentDefinitionElement_)
    {
        // Constructor
        setComponentDefinitionElement(_componentDefinitionElement_);

    }

    @Override
    public Object clone()
    {
        return new AComponentDefinitionElementComponentDefinitionList(
            cloneNode(this._componentDefinitionElement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComponentDefinitionElementComponentDefinitionList(this);
    }

    public PComponentDefinitionElement getComponentDefinitionElement()
    {
        return this._componentDefinitionElement_;
    }

    public void setComponentDefinitionElement(PComponentDefinitionElement node)
    {
        if(this._componentDefinitionElement_ != null)
        {
            this._componentDefinitionElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._componentDefinitionElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._componentDefinitionElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._componentDefinitionElement_ == child)
        {
            this._componentDefinitionElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._componentDefinitionElement_ == oldChild)
        {
            setComponentDefinitionElement((PComponentDefinitionElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
