/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class AEofComponentDefinitionElement extends PComponentDefinitionElement
{
    private TEof _eof_;

    public AEofComponentDefinitionElement()
    {
        // Constructor
    }

    public AEofComponentDefinitionElement(
        @SuppressWarnings("hiding") TEof _eof_)
    {
        // Constructor
        setEof(_eof_);

    }

    @Override
    public Object clone()
    {
        return new AEofComponentDefinitionElement(
            cloneNode(this._eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEofComponentDefinitionElement(this);
    }

    public TEof getEof()
    {
        return this._eof_;
    }

    public void setEof(TEof node)
    {
        if(this._eof_ != null)
        {
            this._eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eof_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._eof_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._eof_ == child)
        {
            this._eof_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._eof_ == oldChild)
        {
            setEof((TEof) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
