/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class ATypeComponentElementType extends PComponentElementType
{
    private PElementType _elementType_;

    public ATypeComponentElementType()
    {
        // Constructor
    }

    public ATypeComponentElementType(
        @SuppressWarnings("hiding") PElementType _elementType_)
    {
        // Constructor
        setElementType(_elementType_);

    }

    @Override
    public Object clone()
    {
        return new ATypeComponentElementType(
            cloneNode(this._elementType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeComponentElementType(this);
    }

    public PElementType getElementType()
    {
        return this._elementType_;
    }

    public void setElementType(PElementType node)
    {
        if(this._elementType_ != null)
        {
            this._elementType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elementType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elementType_ == child)
        {
            this._elementType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elementType_ == oldChild)
        {
            setElementType((PElementType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
