/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.parser;

import at.fhj.swd07.contours.node.*;
import at.fhj.swd07.contours.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTDefinitionIdentifier(@SuppressWarnings("unused") TDefinitionIdentifier node)
    {
        this.index = 0;
    }

    @Override
    public void caseTStart(@SuppressWarnings("unused") TStart node)
    {
        this.index = 1;
    }

    @Override
    public void caseTOutputPath(@SuppressWarnings("unused") TOutputPath node)
    {
        this.index = 2;
    }

    @Override
    public void caseTEof(@SuppressWarnings("unused") TEof node)
    {
        this.index = 3;
    }

    @Override
    public void caseTByte(@SuppressWarnings("unused") TByte node)
    {
        this.index = 4;
    }

    @Override
    public void caseTInteger(@SuppressWarnings("unused") TInteger node)
    {
        this.index = 5;
    }

    @Override
    public void caseTLong(@SuppressWarnings("unused") TLong node)
    {
        this.index = 6;
    }

    @Override
    public void caseTBcd(@SuppressWarnings("unused") TBcd node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 8;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 9;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 10;
    }

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 11;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 12;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 13;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 14;
    }

    @Override
    public void caseTDotdot(@SuppressWarnings("unused") TDotdot node)
    {
        this.index = 15;
    }

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 16;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 17;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 18;
    }

    @Override
    public void caseTDefinitionSeparator(@SuppressWarnings("unused") TDefinitionSeparator node)
    {
        this.index = 19;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 20;
    }

    @Override
    public void caseTPackageIdentifier(@SuppressWarnings("unused") TPackageIdentifier node)
    {
        this.index = 21;
    }

    @Override
    public void caseTCharacterLiteral(@SuppressWarnings("unused") TCharacterLiteral node)
    {
        this.index = 22;
    }

    @Override
    public void caseTIntegerLiteral(@SuppressWarnings("unused") TIntegerLiteral node)
    {
        this.index = 23;
    }

    @Override
    public void caseTHexLiteral(@SuppressWarnings("unused") THexLiteral node)
    {
        this.index = 24;
    }

    @Override
    public void caseTHexByte(@SuppressWarnings("unused") THexByte node)
    {
        this.index = 25;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 26;
    }
}
