/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class ABcdElementType extends PElementType
{
    private TBcd _bcd_;

    public ABcdElementType()
    {
        // Constructor
    }

    public ABcdElementType(
        @SuppressWarnings("hiding") TBcd _bcd_)
    {
        // Constructor
        setBcd(_bcd_);

    }

    @Override
    public Object clone()
    {
        return new ABcdElementType(
            cloneNode(this._bcd_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABcdElementType(this);
    }

    public TBcd getBcd()
    {
        return this._bcd_;
    }

    public void setBcd(TBcd node)
    {
        if(this._bcd_ != null)
        {
            this._bcd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bcd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bcd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bcd_ == child)
        {
            this._bcd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bcd_ == oldChild)
        {
            setBcd((TBcd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
