/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class AFormatDefinition extends PFormatDefinition
{
    private PFormatHeader _formatHeader_;
    private PComponentDefinitions _componentDefinitions_;

    public AFormatDefinition()
    {
        // Constructor
    }

    public AFormatDefinition(
        @SuppressWarnings("hiding") PFormatHeader _formatHeader_,
        @SuppressWarnings("hiding") PComponentDefinitions _componentDefinitions_)
    {
        // Constructor
        setFormatHeader(_formatHeader_);

        setComponentDefinitions(_componentDefinitions_);

    }

    @Override
    public Object clone()
    {
        return new AFormatDefinition(
            cloneNode(this._formatHeader_),
            cloneNode(this._componentDefinitions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormatDefinition(this);
    }

    public PFormatHeader getFormatHeader()
    {
        return this._formatHeader_;
    }

    public void setFormatHeader(PFormatHeader node)
    {
        if(this._formatHeader_ != null)
        {
            this._formatHeader_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formatHeader_ = node;
    }

    public PComponentDefinitions getComponentDefinitions()
    {
        return this._componentDefinitions_;
    }

    public void setComponentDefinitions(PComponentDefinitions node)
    {
        if(this._componentDefinitions_ != null)
        {
            this._componentDefinitions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._componentDefinitions_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formatHeader_)
            + toString(this._componentDefinitions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formatHeader_ == child)
        {
            this._formatHeader_ = null;
            return;
        }

        if(this._componentDefinitions_ == child)
        {
            this._componentDefinitions_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formatHeader_ == oldChild)
        {
            setFormatHeader((PFormatHeader) newChild);
            return;
        }

        if(this._componentDefinitions_ == oldChild)
        {
            setComponentDefinitions((PComponentDefinitions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
