/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class AOutputPath extends POutputPath
{
    private TOutputPath _outputPath_;
    private TLParen _lParen_;
    private TCharacterLiteral _characterLiteral_;
    private TRParen _rParen_;
    private TSemicolon _semicolon_;

    public AOutputPath()
    {
        // Constructor
    }

    public AOutputPath(
        @SuppressWarnings("hiding") TOutputPath _outputPath_,
        @SuppressWarnings("hiding") TLParen _lParen_,
        @SuppressWarnings("hiding") TCharacterLiteral _characterLiteral_,
        @SuppressWarnings("hiding") TRParen _rParen_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setOutputPath(_outputPath_);

        setLParen(_lParen_);

        setCharacterLiteral(_characterLiteral_);

        setRParen(_rParen_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AOutputPath(
            cloneNode(this._outputPath_),
            cloneNode(this._lParen_),
            cloneNode(this._characterLiteral_),
            cloneNode(this._rParen_),
            cloneNode(this._semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOutputPath(this);
    }

    public TOutputPath getOutputPath()
    {
        return this._outputPath_;
    }

    public void setOutputPath(TOutputPath node)
    {
        if(this._outputPath_ != null)
        {
            this._outputPath_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outputPath_ = node;
    }

    public TLParen getLParen()
    {
        return this._lParen_;
    }

    public void setLParen(TLParen node)
    {
        if(this._lParen_ != null)
        {
            this._lParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lParen_ = node;
    }

    public TCharacterLiteral getCharacterLiteral()
    {
        return this._characterLiteral_;
    }

    public void setCharacterLiteral(TCharacterLiteral node)
    {
        if(this._characterLiteral_ != null)
        {
            this._characterLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._characterLiteral_ = node;
    }

    public TRParen getRParen()
    {
        return this._rParen_;
    }

    public void setRParen(TRParen node)
    {
        if(this._rParen_ != null)
        {
            this._rParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rParen_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._outputPath_)
            + toString(this._lParen_)
            + toString(this._characterLiteral_)
            + toString(this._rParen_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._outputPath_ == child)
        {
            this._outputPath_ = null;
            return;
        }

        if(this._lParen_ == child)
        {
            this._lParen_ = null;
            return;
        }

        if(this._characterLiteral_ == child)
        {
            this._characterLiteral_ = null;
            return;
        }

        if(this._rParen_ == child)
        {
            this._rParen_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._outputPath_ == oldChild)
        {
            setOutputPath((TOutputPath) newChild);
            return;
        }

        if(this._lParen_ == oldChild)
        {
            setLParen((TLParen) newChild);
            return;
        }

        if(this._characterLiteral_ == oldChild)
        {
            setCharacterLiteral((TCharacterLiteral) newChild);
            return;
        }

        if(this._rParen_ == oldChild)
        {
            setRParen((TRParen) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
