/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.fhj.swd07.contours.node;

import at.fhj.swd07.contours.analysis.*;

@SuppressWarnings("nls")
public final class TDefinitionSeparator extends Token
{
    public TDefinitionSeparator()
    {
        super.setText("::=");
    }

    public TDefinitionSeparator(int line, int pos)
    {
        super.setText("::=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefinitionSeparator(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefinitionSeparator(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefinitionSeparator text.");
    }
}
